# speficy your container image, such as deepcluster/pytorch:1.0-python3.7 or deepcluster/tensorflow:1.12-python3.6
container_image:

# provide known dataset name or local datasets
dataset_name:
dataset_path:

# number of GPU used to train, default it 1
worker_required: 1

# command to run
# use the enviornment variable $DATASET to access dataset
# and write output to $OUTPUT
command:

# you can also define your config here
# config.yaml will be placed next to main.py
# so you can access your config from code from "./config.yaml"
