# speficy your job type, such as tensorflow and pytorch
job_type: 

# provide known dataset name or local datasets
dataset_name:
dataset_path:

# number of GPU used to train, default it 1
worker_required: 1

# you can also define your config here
# config.yaml will be placed next to main.py
# so you can access your config from code where path will be "./config.yaml"
